// Search Bar
export const FETCH_OPTIONS = 'FETCH_OPTIONS';
export const FETCH_OPTIONS_SUCCESS = 'FETCH_OPTIONS_SUCCESS';
export const FETCH_OPTIONS_FAIL = 'FETCH_OPTIONS_FAIL';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const EXECUTE_SEARCH = 'EXECUTE_SEARCH';
export const EXECUTE_SEARCH_SUCCESS = 'EXECUTE_SEARCH_SUCCESS';
export const EXECUTE_SEARCH_FAIL = 'EXECUTE_SEARCH_FAIL';
export const OPEN_OPTIONS_POPUP = 'OPEN_OPTIONS_POPUP';
export const CLOSE_SEARCH_OPTIONS = 'CLOSE_SEARCH_OPTIONS';
